version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: yarn lint
          command: yarn lint
      - run:
          name: yarn build
          command: yarn build
      - deploy:
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn run deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
